### ISSUE TITLE
Which 3.1 focuser/mid do i print?

### ISSUE THREAD

**Issue by kfechter** [OpenAstroTech/OpenAstroGuider#5]
kind of a dumb question, but I'm at a loss here. I have all the 3.1 files I think I need to print except the mid, focuser. however there are 10 different mid files with different mm values, and im not finding any docs that tell me which one i need to print.

**Comment by Clay2F** [comment]
There is a test print file to find the right tolerance for the mid part. 
the test that fits best is the part which you should youse for the final print

**Comment by kfechter** [comment]
got it, thanks! i'll close this issue
