### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by co2e14** [OpenAstroTech/OpenAstroGuider#7]
Could we have some instructions added to this project? 

What heater?
What custom PCB?
How to install heater?
What does TI/noTI mean in the file name?

**Comment by Trigger-broom-289** [comment]
Hello,

_What heater / PCB_
https://shop.openastrotech.com/collections/openastroguider/products/openastroguider-hardware-only?variant=43638627238155

_How to install heater?_
https://wiki.openastrotech.com/en/OpenAstroGuider/OpenAstroGuiderV3_DewHeater

_TI/noTI_
TI stands for Threaded Insert
